### PR TITLE
Added docker to getting started

### PR DESCRIPTION
**Pull request by alk-automize**
Docker can be useful if you do not want to install azbb directly on your system. And you can have azbb in different versions.

### CODE REVIEW

**Comment by alk-automize** [comment]
Hold on merging this. Seems azbb is dependent on Azure cli

**Comment by Petertaylor9999** [comment]
Hi there - there's actually a docker image for the Azure cli. 

https://hub.docker.com/r/microsoft/azure-cli/

If you specify this as the base image, the rest should work. I don't have time to test right now, but will come back to this later if you're not able to test either. Thank you!

**Comment by alk-automize** [comment]
Thanks, I use azure-cli a lot already. I'll use that as the base image and put azbb on top. Will fix it later today.

**Comment by dcasati** [comment]
I'd be interested to see how you are progressing here as well. I've created my own Dockerfile for this right now: https://github.com/dcasati/azbb-container/blob/master/Dockerfile

**Comment by alktlr** [comment]
I wanted something more lightweight than a full distro. So I tried making a Dockerfile base on azure-cli alpine image, but ran into some issue with windows new lines and nodejs. Below is what I got so far. Hate the last line hacking. The first 3 lines just don't work.

ROM microsoft/azure-cli:latest
RUN apk add --update nodejs
RUN npm install -g @mspnp/azure-building-blocks
# Fix broken node and env on alpine. Sed -i does not work either, hence the moving around
RUN sed 's/node\r/node/' /usr/bin/azbb > /tmp/azbb; chmod +x /tmp/azbb; mv /tmp/azbb /usr/bin/azbb

**Comment by alk-automize** [comment]
Its ready for merge. Sorry for late update.

**Comment by luisgmsft** [comment]
Hi all :) There was an issue with the package. Try with the latest one ([v.2.1.7](https://www.npmjs.com/package/@mspnp/azure-building-blocks))

There's no need for the fix https://github.com/mspnp/template-building-blocks/pull/374#issuecomment-366379535

Please let me know if this helps!

**Comment by Petertaylor9999** [comment]
I can't get this to work - we'll revisit in the near future.

**Pull request closed without merging**
