### PR TITLE
Fix az cli breaking changes

### PR DESCRIPTION
**Pull request by atoakley**

### CODE REVIEW

**Comment by pranavtiwari09** [comment]
@atoakley 
I am using Azure Cloud shell and I have already verified that it is up-to-date. 
I don't see --subscription argument in AZ CLI and I thought that it is missing so I added Subscription extension but it did not help.
I will run this again today sometime and will update here again. 
Thanks for looking.

Anything else you can advise to look for.

**Comment by pranavtiwari09** [comment]
> @atoakley
> I am using Azure Cloud shell and I have already verified that it is up-to-date.
> I don't see --subscription argument in AZ CLI and I thought that it is missing so I added Subscription extension but it did not help.
> I will run this again today sometime and will update here again.
> Thanks for looking.
> 
> Anything else you can advise to look for.

@atoakley 
Getting new error: error: EEXIST: file already exists, mkdir '/home/pranav'
I changed to 'pwd' to root '/'
getting error: error: EEXIST: file already exists, mkdir '/'

Apparently, azbb is trying to first create a directory where I am running command from.
I have nothing installed locally on my machine. I am running it from azure cloud shell. 
So something else is broke. Please help.

**Comment by atoakley** [comment]
@pranavtiwari09 This might be a NodeJS thing. I'm not sure why it would try to create the directory if it exists. Try specifying an output directory with the -o switch and point it to something like "/home/pranav/<something>/parameter-file.json". If that works, I will see if I can recreate the issue and publish a new version. I have not tested with cloud shell, so perhaps it is an incompatibility there as well.

**Comment by pranavtiwari09** [comment]
> @pranavtiwari09 This might be a NodeJS thing. I'm not sure why it would try to create the directory if it exists. Try specifying an output directory with the -o switch and point it to something like "/home/pranav//parameter-file.json". If that works, I will see if I can recreate the issue and publish a new version. I have not tested with cloud shell, so perhaps it is an incompatibility there as well.

@atoakley : No go. Same error :-)
Ye!! that worked:
azbb -g AADesignLab08-hub-vnet-rg -s 3a25883a-eb00-479a-b3ed-f2a11b530037 -l eastus -p ~/hub-vnet.json --deploy -o /home/pranav/output/output.json

  parameters written to /home/pranav/output/output-output-01.json


  parameters written to /home/pranav/output/output-output-02.json

Will run other parameter files and will update you shortly. 
But why? it should work without -o output file - shouldn't it.

**Comment by pranavtiwari09** [comment]
> > @pranavtiwari09 This might be a NodeJS thing. I'm not sure why it would try to create the directory if it exists. Try specifying an output directory with the -o switch and point it to something like "/home/pranav//parameter-file.json". If that works, I will see if I can recreate the issue and publish a new version. I have not tested with cloud shell, so perhaps it is an incompatibility there as well.
> 
> @atoakley : No go. Same error :-)
> Ye!! that worked:
> azbb -g AADesignLab08-hub-vnet-rg -s 3a25883a-eb00-479a-b3ed-f2a11b530037 -l eastus -p ~/hub-vnet.json --deploy -o /home/pranav/output/output.json
> 
> parameters written to /home/pranav/output/output-output-01.json
> 
> parameters written to /home/pranav/output/output-output-02.json
> 
> Will run other parameter files and will update you shortly.
> But why? it should work without -o output file - shouldn't it.

@atoakley : Thank you so much Andrew. It worked. All the parameter files run successfully. 

But the big question is why it works with output file? Wonder if you can investigate or help me understand.

**Comment by atoakley** [comment]
@pranavtiwari09 I think this is caused by a permissions issue inside cloud shell. I was able to recreate the error. Do you have the ability to test this in WSL or a real linux box? It should work there. I am going to work on a fix for cloud shell.

**Comment by atoakley** [comment]
@pranavtiwari09 This should be fixed in PR #416

**Comment by pranavtiwari09** [comment]
> @pranavtiwari09 I think this is caused by a permissions issue inside cloud shell. I was able to recreate the error. Do you have the ability to test this in WSL or a real linux box? It should work there. I am going to work on a fix for cloud shell.

@atoakley : No I don't have WSL or Linux box to test. I have a Mac where I have installed Azure CLI but it doesn't work very well. 

Thank you for looking into this.

**Pull request merged**
